import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  useCasesSidebar : [
    {
      type : 'category',
      label : 'Use Cases',
      link : {
        type : 'generated-index',
        title : 'Use Cases',
        description :
            'See how Harry - Performance Scraper for Oracle Database turns collected performance data into practical investigation workflows.',
        slug : '/',
      },
      items : [ {type : 'autogenerated', dirName : '.'} ],
    },
  ],
};

export default sidebars;
